spring:
  application:
    name: zipkin-service
  profiles:
    active: insecure
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.102.202:3306//old-c2b-800-local?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: bwoiluser
    password: bwoil@123
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    filters: stat
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true

#    druid:
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://192.168.102.202:3306/old-c2b-800-local?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#      username: bwoiluser
#      password: bwoil@123
#      filters: stat
#      maxActive: 30
#      initialSize: 1
#      minIdle: 5
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      maxOpenPreparedStatements: 20
#      removeAbandoned: true
#      removeAbandonedTimeout: 1800
#      logAbandoned: true
# admin登录的用户名和密码


  #单机版
  #    host: 127.0.0.1
  #    port: 6379
  #    password: 123456
  #      pool:
  #        max-idle: 100
  #        min-idle: 1
  #        max-active: 1000
  #        max-wait: -1
  #集群版
#  redis:
#    database: 0
#    cluster:
#      nodes: 192.168.101.227:7001,192.168.101.227:7002,192.168.101.227:7003,192.168.101.228:7001,192.168.101.228:7002,192.168.101.228:7003
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
#    timeout: 10000



server:
  port: 9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.101.221:8088/eureka,http://192.168.101.223:8088/eureka,http://192.168.101.220:8088/eureka
#      defaultZone: http://192.168.101.55:8760/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20


#########性能优化相关####################

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: 1500
      queueSizeRejectionThreshold: 1000
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:                  ##40秒>= ribbon(5000+5000)*2*2
            timeoutInMilliseconds: 40000
#########性能优化相关 end####################

#    health-check-url-path: /actuator/health #2.0后actuator的地址发生了变化
#    metadata-map:
#      "user.name": ${spring.security.user.name}         #These two are needed so that the server
#      "user.password": ${spring.security.user.password} #can access the protected client endpoints

# 2.0开始，actuator默认不开放，所以要设置为开放
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"  #<2>
#  endpoint:
#    health:
#      show-details: ALWAYS



