spring:
  application:
    name: zipkin-service

server:
  port: 9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.101.221:8088/eureka,http://192.168.101.223:8088/eureka,http://192.168.101.220:8088/eureka
#      defaultZone: http://192.168.101.55:8760/eureka
  instance:
    prefer-ip-address: true
